testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "sk_test_51Oo2gwSIbKax4i4DtfTZ9EvscXdgE19zFJ4wRfumTgi5pdz1XHAFfVVwsfmVuShPiwh1x5JXobHPWqhgTaZtJUNO004T41EYnQ" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_fZe9DY5DR7aD09ifYZ" #only needed if using Stripe
client_id = "952718510353-kol2iipa340a9diq901r9oc36ksaj1ui.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
